### ISSUE TITLE
Add support for different weather models

### ISSUE THREAD

**Issue by kytta** [frenck/python-open-meteo#321]
# Problem/Motivation

By default, open-meteo queries all models and returns the best one for the location. However, there are separate API endpoints for weather models that can return more (or less) data. For example, at `/v1/dwd-icon`, one can get 15-minute-forecasts.

## Expected behavior / Proposed changes

I'd love to see all endpoints implemented as separate methods:

- [DWD ICON](https://open-meteo.com/en/docs/dwd-api)
- [NOAA GFS](https://open-meteo.com/en/docs/gfs-api)
- [MeteoFrance](https://open-meteo.com/en/docs/meteofrance-api)
- [ECMWF](https://open-meteo.com/en/docs/ecmwf-api)
- [JMA](https://open-meteo.com/en/docs/jma-api)
- [MET Norway](https://open-meteo.com/en/docs/metno-api)
- [GEM](https://open-meteo.com/en/docs/gem-api)

**Comment by kytta** [comment]
On an unrelated note, @frenck, do you still maintain the project? I see dependabot PRs getting merged, but there hasn't been a release, and the README says the project is unmaintained. I'd like to continue the project, and I don't know whether I should send patches here or maintain my own fork

**Comment by frenck** [comment]
Yes, and no need to ping me for stuff like that. Thanks 👍

**Comment by frenck** [comment]
not stale :)
